# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbfc8fecaff022be762d47bd16211a3df68d99e6276bdcf8f819663bc1652ef8b2c408df6f9be5f06c2eca2026d17603b42221fdb8007eb90ca3a14493b65e2b

test:
  secret_key_base: 3ea8d8c5d0e235d6ff4fa48e68ebef84bcd8d1e4242d2861bcf4a759da7efd12ad88bc08b7357b54fcdee67b852ba28bd21aeac5eef40bf22321fa0c8dccce18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
